language.Add("tool.koptilnya_holo_builder.name", "Holo Builder")
language.Add("tool.koptilnya_holo_builder.desc", "Build anything with holograms")
language.Add("tool.koptilnya_holo_builder.left_spawn", "Left click to spawn a controller")
language.Add("Undone_koptilnya_holo_builder", "Undone Holo Builder")
language.Add("Undone_Holo Builder", "Undone Holo Builder")
language.Add("Cleanup_koptilnya_holo_builder", "Holo Builder")
language.Add("Cleaned_koptilnya_holo_builder", "Cleaned Holo Builders")
